spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5433/blog?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC}
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: validate
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server.port: ${PORT:8080}

#Multipart file properties
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
storage.location: ./upload

#Email service properties
spring.mail.host: smtp.mail.ru
spring.mail.port: 587
spring.mail.username: myblogtest@mail.ru
spring.mail.password: 
spring.mail.properties.mail.transport.protocol: smtp
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.debug: true
spring.mail.properties.mail.smtp.ssl.trust: smtp.mail.ru


